# Generated by Django 3.1.5 on 2021-01-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=120)),
                ('Description', models.CharField(max_length=120)),
                ('PhotoName', models.CharField(max_length=120)),
                ('Tags', models.JSONField()),
            ],
        ),
    ]
