# Generated by Django 3.1.5 on 2021-01-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='GithubLink',
            field=models.CharField(default='n/a', max_length=120),
            preserve_default=False,
        ),
    ]
