# Generated by Django 3.1.5 on 2021-01-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210113_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='DemoLink',
            field=models.CharField(default='null', max_length=120),
            preserve_default=False,
        ),
    ]
